name: webflow-git

env:
  SITE: https://alpinejs.webflow.io/

on:
  workflow_dispatch

jobs:
  track:
    name: Track Webflow site changes

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Webflow Site ${{ env.SITE }}
        uses: loomchild/webflow-get@master
        with:
          site: ${{ env.SITE }}
