name: webflow-git


on:
  workflow_dispatch
  schedule:
    - cron:  '2 * * * *'

jobs:
  track:
    name: Track Webflow site changes

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Site
        run: |
          if [ -e $GITHUB_WORKSPACE/.site ]
          then
            SITE=`cat $GITHUB_WORKSPACE/.site | xargs`
            echo "SITE=$SITE" >> $GITHUB_ENV
          else
            echo ".site file not found, skipping"
            exit 1
          fi

          if [ -z "$SITE" ]
          then
            echo ".site file is empty, skipping"
            exit 1
          fi

      - name: Get Webflow Site ${{ env.SITE }}
        uses: loomchild/webflow-get@master
        with:
          site: ${{ env.SITE }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Webflow Git
          author_email: webflowgit@local
          message: 'Site updated'
