name: webflow-git


on:
  workflow_dispatch

jobs:
  track:
    name: Track Webflow site changes

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Site
        run: echo "SITE=$(cat .site | xargs)" >> $GITHUB_ENV

      - name: Get Webflow Site ${{ env.SITE }}
        uses: loomchild/webflow-get@master
        with:
          site: ${{ env.SITE }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Webflow Git
          author_email: webflowgit@local
          message: 'Site updated'
